### ISSUE TITLE
请教下这个工具的更新是在哪里找到的

### ISSUE THREAD

**Issue by anpu2018** [gitccl/Navicat-key#1]
以前一直用的12版本的，15之后用不了了，一直没找到这个工具更新下载的地方

**Comment by gitccl** [comment]
15可以用啊，我就是15的

**Comment by gitccl** [comment]
> 以前一直用的12版本的，15之后用不了了，一直没找到这个工具更新下载的地方

15可以用啊，我就是15的

**Comment by anpu2018** [comment]
我的意思是，我之前用的一个版本，当navicat升级到15以后用不了了，昨天看到您的项目，项目里提供的这个可以破15，想问下您这个版本在哪里找到的，我在github上没找到最原始的那个项目的更新文件

**Comment by gitccl** [comment]
> 我的意思是，我之前用的一个版本，当navicat升级到15以后用不了了，昨天看到您的项目，项目里提供的这个可以破15，想问下您这个版本在哪里找到的，我在github上没找到最原始的那个项目的更新文件

这个具体我也忘了，我也是看别人的帖子
